### ISSUE TITLE
LV Crash when setting PNG compression to 0

### ISSUE THREAD

**Issue by kleinsimon** [dataflowg/g-image#8]
Very nice work, this library makes multiple hacked libs of myself obsolete.

During testing, I stumbled upon the following unexpected behavior:

When settings the compression for PNG to 0, LV crashes hard. If 0 is an unexpected value, maybe a in range and coerce is missing.

**Comment by dataflowg** [comment]
Hi @kleinsimon, thanks for the comment, and raising the issue.

When saving png, compression level 0 is one of the supported levels (0-10 inclusive). I've just tried it with the following snippet and didn't see a crash (using LV2020 32-bit on Windows 10).

![g-image-png-0](https://user-images.githubusercontent.com/44384905/217270443-79e6a16d-5d43-4a39-82da-3f643c18b6df.png)

- What version of LV, bitness, and OS are you seeing the crash?
- Do all images you've tried crash when saving with compression level 0?
- What's the image's dimension and bit depth?
- Do other compression levels work for the problematic images?

If there's any code or images you can share that'd be helpful.

Edit: After writing all that, I tested saving the png with level 0 to memory rather than to disk, and am seeing error 1097 _exception occurred within the external code_. Are you saving the png to memory?

**Comment by kleinsimon** [comment]
Ah yes, I forgot to mention that. I wrote to memory. 
Setup: LV 2020 R2, 64 bit, Windows 10
I can reproduce this on another PC using you snippet. It seems independent on the actual image data.

**Comment by dataflowg** [comment]
Found and fixed the issue, thanks again for the bug report. I'll aim to package up a new VIPM build over the weekend.

**Comment by dataflowg** [comment]
Fix available in v0.3.0 ([github](https://github.com/dataflowg/g-image/releases/tag/v0.3.0), [VIPM](https://www.vipm.io/package/dataflow_g_lib_g_image/))
